version: '3'
services:
  ${WEB_CONTAINER_NAME}:
    container_name: ${WEB_CONTAINER_NAME}
    restart: always
    image: registry.cn-shenzhen.aliyuncs.com/piupuer/gin-web:${WEB_TAG}
    working_dir: /app/gin-web-prod
    environment:
      TZ: Asia/Shanghai
      CFG_SYSTEM_MACHINE_ID: '${MACHINE_ID}'
      CFG_SYSTEM_USE_REDIS: 'true'
      CFG_REDIS_SENTINEL_ENABLE: 'true'
      CFG_REDIS_SENTINEL_MASTER_NAME: '${REDIS_MASTER_NAME}'
      CFG_REDIS_SENTINEL_ADDRESSES: '${WEB_REDIS_SENTINEL_ADDRESSES}'
      CFG_REDIS_PASSWORD: '${REDIS_PASS}'
      CFG_MYSQL_HOST: '${WEB_MYSQL_HOST}'
      CFG_MYSQL_PORT: '${WEB_MYSQL_PORT}'
      CFG_MYSQL_PASSWORD: '${WEB_MYSQL_PASSWORD}'
    volumes:
      - ${WEB_CONTAINER_NAME}-logs-data:/app/gin-web-prod/logs
      - ${WEB_CONTAINER_NAME}-conf-data:/app/gin-web-prod/conf
    ports:
      - ${WEB_PORT}:8080
      - ${WEB_PPROF_PORT}:8005

volumes:
  ${WEB_CONTAINER_NAME}-logs-data:
  ${WEB_CONTAINER_NAME}-conf-data:
