version: '3'
services:
  ${WEB_CONTAINER_NAME}:
    container_name: ${WEB_CONTAINER_NAME}
    restart: always
    image: registry.cn-shenzhen.aliyuncs.com/piupuer/gin-web:${WEB_TAG}
    working_dir: /app/gin-web-prod
    environment:
      TZ: Asia/Shanghai
      CFG_SYSTEM_MACHINE_ID: '${MACHINE_ID}'
      CFG_SYSTEM_USE_REDIS: 'true'
      CFG_REDIS_URI: '${WEB_REDIS_URI}'
      CFG_MYSQL_URI: '${WEB_MYSQL_URI}'
    volumes:
      - ${WEB_CONTAINER_NAME}-logs-data:/app/gin-web-prod/logs
      - ${WEB_CONTAINER_NAME}-conf-data:/app/gin-web-prod/conf
    ports:
      - ${WEB_PORT}:8080
      - ${WEB_PPROF_PORT}:8005

volumes:
  ${WEB_CONTAINER_NAME}-logs-data:
  ${WEB_CONTAINER_NAME}-conf-data:
